---
all:
  children:
    windows:
      hosts:
        dev-win-01.internal.bank:
        dev-win-02.internal.bank:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986

    linux:
      hosts:
        dev-linux-01.internal.bank:
        dev-linux-02.internal.bank:
      vars:
        ansible_connection: ssh
        ansible_port: 22

  vars:
    env: dev
