apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ansible-ee-poc-run-
spec:
  pipelineRef:
    name: ansible-ee-poc
  params:
    - name: GIT_URL
      value: https://github.com/your-org/ansible-ee.git   # update me
    - name: GIT_REVISION
      value: feat/poc
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/your-namespace/ansible-ee:poc  # update me
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
